/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoArchivos_Cine;

/**
 *
 * @author yogg-saron
 */
public class seleccionCampos extends javax.swing.JFrame {

    /**
     * Creates new form seleccionCampos
     */
    public seleccionCampos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccion de Butacas");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(60, 51, 87));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(246, 245, 255));
        jLabel3.setText("B");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(246, 245, 255));
        jLabel4.setText("A");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(246, 245, 255));
        jLabel5.setText("A");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(246, 245, 255));
        jLabel6.setText("B");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 245, 255));
        jLabel7.setText("C");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(246, 245, 255));
        jLabel8.setText("D");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(246, 245, 255));
        jLabel9.setText("E");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(246, 245, 255));
        jLabel10.setText("E");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(246, 245, 255));
        jLabel11.setText("C");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(246, 245, 255));
        jLabel12.setText("D");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jButton1.setText("11");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 40, -1));

        jButton2.setText("11");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 40, -1));

        jButton3.setText("11");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 40, -1));

        jButton4.setText("11");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 40, -1));

        jButton5.setText("11");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, -1));

        jButton6.setText("7");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 40, -1));

        jButton7.setText("7");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 40, -1));

        jButton8.setText("7");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 40, -1));

        jButton9.setText("7");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 40, -1));

        jButton10.setText("7");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 40, -1));

        jButton11.setText("6");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 40, -1));

        jButton12.setText("6");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 40, -1));

        jButton13.setText("6");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 40, -1));

        jButton14.setText("6");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 40, -1));

        jButton15.setText("6");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 40, -1));

        jButton16.setText("5");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 40, -1));

        jButton17.setText("5");
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 40, -1));

        jButton18.setText("5");
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 40, -1));

        jButton19.setText("5");
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 40, -1));

        jButton20.setText("5");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 40, -1));

        jButton21.setText("4");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 40, -1));

        jButton22.setText("4");
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 40, -1));

        jButton23.setText("4");
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 40, -1));

        jButton24.setText("4");
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 40, -1));

        jButton25.setText("4");
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 40, -1));

        jButton26.setText("3");
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 40, -1));

        jButton27.setText("3");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 40, -1));

        jButton28.setText("3");
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 40, -1));

        jButton29.setText("3");
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 40, -1));

        jButton30.setText("3");
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 40, -1));

        jButton31.setText("2");
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 40, -1));

        jButton32.setText("2");
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 40, -1));

        jButton33.setText("2");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 40, -1));

        jButton34.setText("2");
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 40, -1));

        jButton35.setText("2");
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 40, -1));

        jButton36.setText("1");
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 40, -1));

        jButton37.setText("1");
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 40, -1));

        jButton38.setText("1");
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 40, -1));

        jButton39.setText("1");
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 40, -1));

        jButton40.setText("1");
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 40, -1));

        jButton41.setText("7");
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 40, -1));

        jButton42.setText("7");
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 40, -1));

        jButton43.setText("7");
        getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 40, -1));

        jButton44.setText("7");
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 40, -1));

        jButton45.setText("7");
        getContentPane().add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 40, -1));

        jButton46.setText("6");
        getContentPane().add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 40, -1));

        jButton47.setText("6");
        getContentPane().add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 40, -1));

        jButton48.setText("6");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 40, -1));

        jButton49.setText("6");
        getContentPane().add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 40, -1));

        jButton50.setText("6");
        getContentPane().add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 40, -1));

        jButton51.setText("5");
        getContentPane().add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 40, -1));

        jButton52.setText("5");
        getContentPane().add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 40, -1));

        jButton53.setText("5");
        getContentPane().add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 40, -1));

        jButton54.setText("5");
        getContentPane().add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 40, -1));

        jButton55.setText("5");
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 40, -1));

        jButton56.setText("10");
        getContentPane().add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 40, -1));

        jButton57.setText("10");
        getContentPane().add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 40, -1));

        jButton58.setText("8");
        getContentPane().add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 40, -1));

        jButton59.setText("8");
        getContentPane().add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 40, -1));

        jButton60.setText("9");
        getContentPane().add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 40, -1));

        jButton61.setText("9");
        getContentPane().add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 40, -1));

        jButton62.setText("8");
        getContentPane().add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 40, -1));

        jButton63.setText("10");
        getContentPane().add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 40, -1));

        jButton64.setText("10");
        getContentPane().add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 40, -1));

        jButton65.setText("8");
        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 40, -1));

        jButton66.setText("9");
        jButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton66ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 40, -1));

        jButton67.setText("8");
        getContentPane().add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 40, -1));

        jButton68.setText("10");
        getContentPane().add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 40, -1));

        jButton69.setText("9");
        getContentPane().add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 40, -1));

        jButton70.setText("9");
        jButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton70ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 40, -1));

        jPanel1.setBackground(new java.awt.Color(75, 43, 104));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imax.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton70ActionPerformed

    private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton66ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton65ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seleccionCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seleccionCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seleccionCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seleccionCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seleccionCampos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
