
package ProyectoArchivos_Cine;

/**
 *
 * @author yogg-saron
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;
public class seleccionCampos extends javax.swing.JFrame {

    /*Creamos el arraylist par almacenar los datos*/
    ArrayList <Reservacion> lista = new ArrayList <Reservacion>();
    String tipoTicket = " ", tipoPelicula=" ";
    
    public seleccionCampos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_cantidad_tiquetes = new javax.swing.JTextField();
        txt_nombre_completo = new javax.swing.JTextField();
        txt_correo_electronico = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        Btn_Atras = new javax.swing.JButton();
        txt_tipo_tiquete = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Btn_Pagar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txt_tipoTicket = new javax.swing.JTextField();
        txt_peliculas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccion de Butacas");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(60, 51, 87));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(246, 245, 255));
        jLabel3.setText("B");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(246, 245, 255));
        jLabel4.setText("A");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(246, 245, 255));
        jLabel5.setText("A");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(246, 245, 255));
        jLabel6.setText("B");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(246, 245, 255));
        jLabel7.setText("C");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(246, 245, 255));
        jLabel8.setText("D");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(246, 245, 255));
        jLabel9.setText("E");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(246, 245, 255));
        jLabel10.setText("E");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(246, 245, 255));
        jLabel11.setText("C");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(246, 245, 255));
        jLabel12.setText("D");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton1.setText("14");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 40, -1));

        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton2.setText("14");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 40, -1));

        jButton3.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton3.setText("14");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 40, -1));

        jButton4.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton4.setText("14");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 40, -1));

        jButton5.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton5.setText("14");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 40, -1));

        jButton6.setText("7");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 40, -1));

        jButton7.setText("7");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 40, -1));

        jButton8.setText("7");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 40, -1));

        jButton9.setText("7");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 40, -1));

        jButton10.setText("7");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 40, -1));

        jButton11.setText("6");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 40, -1));

        jButton12.setText("6");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 40, -1));

        jButton13.setText("6");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 40, -1));

        jButton14.setText("6");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 40, -1));

        jButton15.setText("6");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 40, -1));

        jButton16.setText("5");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 40, -1));

        jButton17.setText("5");
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 40, -1));

        jButton18.setText("5");
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 40, -1));

        jButton19.setText("5");
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 40, -1));

        jButton20.setText("5");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 40, -1));

        jButton21.setText("4");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 40, -1));

        jButton22.setText("4");
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 40, -1));

        jButton23.setText("4");
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 40, -1));

        jButton24.setText("4");
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 40, -1));

        jButton25.setText("4");
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 40, -1));

        jButton26.setText("3");
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 40, -1));

        jButton27.setText("3");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 40, -1));

        jButton28.setText("3");
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 40, -1));

        jButton29.setText("3");
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 40, -1));

        jButton30.setText("3");
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 40, -1));

        jButton31.setText("2");
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 40, -1));

        jButton32.setText("2");
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 40, -1));

        jButton33.setText("2");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 40, -1));

        jButton34.setText("2");
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 40, -1));

        jButton35.setText("2");
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 40, -1));

        jButton36.setText("1");
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 40, -1));

        jButton37.setText("1");
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 40, -1));

        jButton38.setText("1");
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 40, -1));

        jButton39.setText("1");
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 40, -1));

        jButton40.setText("1");
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 40, -1));

        jButton41.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton41.setText("10");
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 40, -1));

        jButton42.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton42.setText("10");
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 40, -1));

        jButton43.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton43.setText("10");
        getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 40, -1));

        jButton44.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton44.setText("10");
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 40, -1));

        jButton45.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton45.setText("10");
        getContentPane().add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 40, -1));

        jButton46.setText("9");
        getContentPane().add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 40, -1));

        jButton47.setText("9");
        getContentPane().add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 40, -1));

        jButton48.setText("9");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 40, -1));

        jButton49.setText("9");
        getContentPane().add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 40, -1));

        jButton50.setText("9");
        getContentPane().add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 40, -1));

        jButton51.setText("8");
        getContentPane().add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 40, -1));

        jButton52.setText("8");
        getContentPane().add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 40, -1));

        jButton53.setText("8");
        getContentPane().add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 40, -1));

        jButton54.setText("8");
        getContentPane().add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 40, -1));

        jButton55.setText("8");
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 40, -1));

        jButton56.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton56.setText("13");
        getContentPane().add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 40, -1));

        jButton57.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton57.setText("13");
        getContentPane().add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 40, -1));

        jButton58.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton58.setText("11");
        getContentPane().add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 40, -1));

        jButton59.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton59.setText("11");
        getContentPane().add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 40, -1));

        jButton60.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton60.setText("12");
        getContentPane().add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 40, -1));

        jButton61.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton61.setText("12");
        getContentPane().add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 40, -1));

        jButton62.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton62.setText("11");
        getContentPane().add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 40, -1));

        jButton63.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton63.setText("13");
        getContentPane().add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 40, -1));

        jButton64.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton64.setText("13");
        getContentPane().add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 40, -1));

        jButton65.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton65.setText("11");
        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 40, -1));

        jButton66.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton66.setText("12");
        jButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton66ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 40, -1));

        jButton67.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton67.setText("11");
        getContentPane().add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 40, -1));

        jButton68.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton68.setText("13");
        getContentPane().add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 40, -1));

        jButton69.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton69.setText("12");
        getContentPane().add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 40, -1));

        jButton70.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jButton70.setText("12");
        jButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton70ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 40, -1));

        jLabel13.setFont(new java.awt.Font("Abyssinica SIL", 2, 24)); // NOI18N
        jLabel13.setForeground(java.awt.Color.orange);
        jLabel13.setText("Formulario de Reservación");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Tipo de tiquete");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Nombre Completo: ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel15.setBackground(java.awt.Color.white);
        jLabel15.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Correo Electronico: ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel16.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Cedula: ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel17.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Cantidad de tiquetes: ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        jLabel18.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Telefono: ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 2, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.orange);
        jLabel1.setText("Seleccione Butacas: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));
        getContentPane().add(txt_cantidad_tiquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 80, -1));
        getContentPane().add(txt_nombre_completo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 270, -1));

        txt_correo_electronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correo_electronicoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_correo_electronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 210, -1));
        getContentPane().add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 210, -1));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 210, -1));

        Btn_Atras.setText("Atras");
        Btn_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txt_tipo_tiquete.setFont(new java.awt.Font("Abyssinica SIL", 2, 12)); // NOI18N
        txt_tipo_tiquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adulto Mayor", "Adulto", "Joven", "Niño" }));
        txt_tipo_tiquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tipo_tiqueteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tipo_tiquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 120, -1));

        jPanel1.setBackground(java.awt.Color.black);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imax.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");

        jLabel20.setFont(new java.awt.Font("Abyssinica SIL", 2, 18)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("Seleccione Pelicula: ");

        Btn_Pagar.setText("Pagar");
        Btn_Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PagarActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("Seleccionado: ");

        txt_tipoTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tipoTicketActionPerformed(evt);
            }
        });

        txt_peliculas.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        txt_peliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BladeBlade Runner - Double Feature", "It - El payaso diabolico", "NinjaGo - Lego", "Battle of the Sexes" }));
        txt_peliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_peliculasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(txt_tipoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel20)
                .addGap(54, 54, 54)
                .addComponent(txt_peliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Pagar)
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tipoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Btn_Pagar)
                    .addComponent(txt_peliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton70ActionPerformed

    private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton66ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton65ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_tipo_tiqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tipo_tiqueteActionPerformed
        // TODO add your handling code here:
        txt_tipoTicket.setText(txt_tipo_tiquete.getSelectedItem().toString());
        tipoTicket = txt_tipo_tiquete.getSelectedItem().toString();
    }//GEN-LAST:event_txt_tipo_tiqueteActionPerformed

    private void txt_correo_electronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correo_electronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correo_electronicoActionPerformed

    private void Btn_PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PagarActionPerformed
        // TODO add your handling code here:
        Reservacion reserva = new Reservacion();
        
        reserva.setNombre_completo(txt_nombre_completo.getText());
        reserva.setCorreo_electronico(txt_correo_electronico.getText());
        reserva.setCedula(txt_cedula.getText());
        reserva.setTelefono(txt_telefono.getText());
        reserva.setTipo_tiquete(tipoTicket);
        reserva.setCantidad_tiquetes(txt_cantidad_tiquetes.getText());
        tipoPelicula= txt_peliculas.getSelectedItem().toString();
        reserva.setPelicula(tipoPelicula);
        
        lista.add(reserva);
        
        int tickets = Integer.parseInt(reserva.getCantidad_tiquetes());
        int total = tickets*2000;
        String totaltickets = Integer.toString(total);
        
        /*JOptionPane.showMessageDialog(rootPane,"\nResumen de solicitud:\n"
            +"Nombre:        "+reserva.getNombre_completo()+"\n"
            +"Correo:        "+reserva.getCorreo_electronico()+"\n"
            +"Cedula:        "+reserva.getCedula()+"\n"
            +"Telefono:      "+reserva.getTelefono()+"\n"
            +"Tipo tiquete:  "+reserva.getTipo_tiquete()+"\n"
            +"Total a pagar: "+totaltickets+"\n"
            +"Pelicula:      "+reserva.getPelicula());*/
                
        ResumenReservacion abrir = new ResumenReservacion();
        abrir.setVisible(true);
        this.setVisible(false);        
        
        ResumenReservacion.txt_nombre_completo.setText(txt_nombre_completo.getText());
        ResumenReservacion.txt_correo_electronico.setText(txt_correo_electronico.getText());
        ResumenReservacion.txt_cedula.setText(txt_cedula.getText());
        ResumenReservacion.txt_telefono.setText(txt_telefono.getText()); 
        ResumenReservacion.txt_tipo_tiquete.setText(tipoTicket);
        ResumenReservacion.txt_pelicula.setText(tipoPelicula);
        ResumenReservacion.txt_total.setText(totaltickets);
    }//GEN-LAST:event_Btn_PagarActionPerformed

    private void Btn_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AtrasActionPerformed
        // TODO add your handling code here:
            principal abrir = new principal();
            abrir.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_Btn_AtrasActionPerformed

    private void txt_tipoTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tipoTicketActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_txt_tipoTicketActionPerformed

    private void txt_peliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_peliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_peliculasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        principal princ = new principal();
        princ.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seleccionCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seleccionCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seleccionCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seleccionCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seleccionCampos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Atras;
    private javax.swing.JButton Btn_Pagar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_cantidad_tiquetes;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_correo_electronico;
    private javax.swing.JTextField txt_nombre_completo;
    private javax.swing.JComboBox<String> txt_peliculas;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_tipoTicket;
    private javax.swing.JComboBox<String> txt_tipo_tiquete;
    // End of variables declaration//GEN-END:variables
}
